- name: picture
  contents:
  - name: picture
    type: EssencePicture
    validate:
    - presence

- name: vimeo_queen
  unique: true
  contents:
  - name: vimeo_code
    type: EssenceHtml
    validate:
    - presence

- name: sound
  contents:
  - name: ogg_file
    type: EssenceFile
  - name: mp3_file
    type: EssenceFile

- name: description
  unique: true
  contents:
  - name: title
    type: EssenceText
  - name: year
    type: EssenceSelect
    settings:
      select_values:
        - 1995
        - 1996
        - 1997
        - 1998
        - 1999
        - 2000
        - 2001
        - 2002
        - 2003
        - 2004
        - 2005
        - 2006
        - 2007
        - 2008
        - 2009
        - 2010
        - 2011
        - 2012
        - 2013
        - 2014
        - 2015
        - 2016
        - 2017
        - 2018
        - 2019
        - 2020
        - 2021
        - 2022
        - 2023
        - 2024
        - 2025
        - 2026
        - 2027
        - 2028
        - 2029
  - name: media
    type: EssenceText
  - name: body
    type: EssenceRichtext

- name: heading
  contents:
  - name: body
    type: EssenceText
    validate:
    - presence

- name: paragraph
  contents:
  - name: body
    type: EssenceRichtext
    validate:
    - presence

- name: image_slider
  unique: true
  nestable_elements:
  - image_slider_picture

- name: image_slider_picture
  compact: true
  contents:
  - name: picture
    type: EssencePicture

- name: image_gallery
  unique: true
  nestable_elements:
  - image_gallery_picture

- name: image_gallery_picture
  compact: true
  contents:
  - name: picture
    type: EssencePicture
    settings:
      crop: true
