- name: picture
  ingredients:
  - role: picture
    type: Picture
    validate:
    - presence

- name: vimeo_queen
  unique: true
  ingredients:
  - role: vimeo_code
    type: Html
    validate:
    - presence

- name: sound
  ingredients:
  - role: ogg_file
    type: File
  - role: mp3_file
    type: File

- name: description
  unique: true
  ingredients:
  - role: title
    type: Text
  - role: year
    type: Select
    settings:
      select_values:
        - 1995
        - 1996
        - 1997
        - 1998
        - 1999
        - 2000
        - 2001
        - 2002
        - 2003
        - 2004
        - 2005
        - 2006
        - 2007
        - 2008
        - 2009
        - 2010
        - 2011
        - 2012
        - 2013
        - 2014
        - 2015
        - 2016
        - 2017
        - 2018
        - 2019
        - 2020
        - 2021
        - 2022
        - 2023
        - 2024
        - 2025
        - 2026
        - 2027
        - 2028
        - 2029
  - role: media
    type: Text
  - role: body
    type: Richtext

- name: heading
  ingredients:
  - role: body
    type: Text
    validate:
    - presence

- name: paragraph
  ingredients:
  - role: body
    type: Richtext
    validate:
    - presence

- name: image_slider
  unique: true
  nestable_elements:
  - image_slider_picture

- name: image_slider_picture
  compact: true
  ingredients:
  - role: picture
    type: Picture

- name: image_gallery
  unique: true
  nestable_elements:
  - image_gallery_picture

- name: image_gallery_picture
  compact: true
  ingredients:
  - role: picture
    type: Picture
    settings:
      crop: true
