# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: start
  unique: true
  elements:
    - picture
  autogenerate:
    - picture

- name: link
  redirects_to_external: true

- name: works
  unique: true

- name: work
  unique: false
  elements:
  - vimeo_queen
  - sound
  - image_slider
  - image_gallery
  - description
  - vimeo_gallery
  autogerate:
  - image_slider
  - description
  - image_gallery
